global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'planner-service'
    static_configs:
      - targets: ['planner-service:8000']
    metrics_path: /metrics
    scrape_interval: 5s

  - job_name: 'frontend-service'
    static_configs:
      - targets: ['frontend-service:8501']
    metrics_path: /metrics
    scrape_interval: 5s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch:9200']
