apiVersion: v1
kind: Namespace
metadata:
  name: ai-planner
  labels:
    name: ai-planner
    version: v1.0.0
---
# ConfigMap for shared configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-planner-config
  namespace: ai-planner
data:
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
  REDIS_HOST: "redis-service"
  ELASTICSEARCH_HOST: "elasticsearch-service"
  MONITORING_HOST: "monitoring-service"
  CONFIG_HOST: "config-service"
  AUTH_HOST: "auth-service"
  NOTIFICATION_HOST: "notification-service"
  
  # Rate limiting
  RATE_LIMIT_REQUESTS: "100"
  RATE_LIMIT_WINDOW: "3600"
  
  # Cache configuration
  CACHE_TTL: "3600"
  
  # Circuit breaker
  CIRCUIT_BREAKER_THRESHOLD: "5"
  CIRCUIT_BREAKER_TIMEOUT: "60"
---
# Secret for sensitive configuration
apiVersion: v1
kind: Secret
metadata:
  name: ai-planner-secrets
  namespace: ai-planner
type: Opaque
data:
  GROQ_API_KEY: ""  # Base64 encoded API key
  JWT_SECRET_KEY: YWktcGxhbm5lci1zZWNyZXQta2V5LWNoYW5nZS1pbi1wcm9kdWN0aW9u  # ai-planner-secret-key-change-in-production
  GRAFANA_PASSWORD: YWRtaW4xMjM=  # admin123
---
# Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-planner-sa
  namespace: ai-planner
---
# RBAC
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ai-planner
  name: ai-planner-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ai-planner-rolebinding
  namespace: ai-planner
subjects:
- kind: ServiceAccount
  name: ai-planner-sa
  namespace: ai-planner
roleRef:
  kind: Role
  name: ai-planner-role
  apiGroup: rbac.authorization.k8s.io
